/** Local luxury groom couture imagery — Aman Groom Studio */
const img = (path: string) => `/images/${path}`;

export const IMAGES = {
  hero: img("hero-main.png"),
  adminLogin: img("admin-login-hero.png"),
  promo: img("promo-banner.png"),
  bespoke: img("bespoke-tailoring.png"),
  store: img("store-interior.png"),
  storeAlt: img("store-showroom.png"),
  logo: "/logo.png",
  categories: {
    sherwanis: img("product-maharaja-sherwani.png"),
    tuxedos: img("product-imperial-tuxedo.png"),
    indoWestern: img("product-indo-western.png"),
    kurtaSets: img("product-kurta-set.png"),
    reception: img("product-reception-blazer.png"),
    accessories: img("product-accessories.png"),
  },
  collections: {
    sherwanis: img("product-dynasty-sherwani.png"),
    tuxedos: img("product-platinum-tuxedo.png"),
    indoWestern: img("product-champagne-bandhgala.png"),
    reception: img("product-sangeet-blazer.png"),
    wedding: img("product-nizam-achkan.png"),
  },
  products: {
    maharajaSherwani: img("product-maharaja-sherwani.png"),
    imperialTuxedo: img("product-imperial-tuxedo.png"),
    indoWestern: img("product-indo-western.png"),
    kurtaSet: img("product-kurta-set.png"),
    accessories: img("product-accessories.png"),
    receptionBlazer: img("product-reception-blazer.png"),
    jodhpuri: img("product-jodhpuri.png"),
    bespoke: img("bespoke-tailoring.png"),
    nizamAchkan: img("product-nizam-achkan.png"),
    dynastySherwani: img("product-dynasty-sherwani.png"),
    champagneBandhgala: img("product-champagne-bandhgala.png"),
    haldiKurta: img("product-haldi-kurta.png"),
    platinumTuxedo: img("product-platinum-tuxedo.png"),
    sangeetBlazer: img("product-sangeet-blazer.png"),
    safaStoleSet: img("product-safa-stole-set.png"),
    mojariSet: img("product-mojari-set.png"),
  },
  gallery: [
    img("product-maharaja-sherwani.png"),
    img("product-dynasty-sherwani.png"),
    img("product-nizam-achkan.png"),
    img("product-imperial-tuxedo.png"),
    img("product-platinum-tuxedo.png"),
    img("product-indo-western.png"),
    img("product-champagne-bandhgala.png"),
    img("product-kurta-set.png"),
    img("product-haldi-kurta.png"),
    img("product-jodhpuri.png"),
    img("product-reception-blazer.png"),
    img("product-sangeet-blazer.png"),
    img("product-accessories.png"),
    img("product-safa-stole-set.png"),
    img("product-mojari-set.png"),
    img("hero-main.png"),
  ],
} as const;
